config/routes.rb
Rails.application.routes.draw do

  resources :surveys do 
    resources :respondents
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  
  belongs_to :question
  belongs_to :respondent
  
  has_many :answer_options
  accepts_nested_attributes_for :answer_options

end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question_option
  belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  
  belongs_to :survey
  
  has_many :question_options
  has_many :answers

  accepts_nested_attributes_for :question_options

end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question
  has_many :answer_options
end

app/models/respondent.rb
class Respondent < ApplicationRecord
  
  belongs_to :survey
  
  has_many :answers

  accepts_nested_attributes_for :answers

end

app/models/survey.rb
class Survey < ApplicationRecord
    
    has_many :questions
    has_many :respondents

    accepts_nested_attributes_for :questions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/respondents_controller.rb
class RespondentsController < ApplicationController
  before_action :set_respondent, only: [:show, :edit, :update, :destroy]
  before_action :set_survey, only: [:new, :edit, :create]

  # GET /respondents
  # GET /respondents.json
  def index
    @respondents = Respondent.all
  end

  # GET /respondents/1
  # GET /respondents/1.json
  def show
  end

  # GET /respondents/new
  def new
    @survey = Survey.find(params[:survey_id])
    @respondent = Respondent.new
    @answer = @respondent.answers.build
    @answer_option = @answer.answer_options.build
  end

  # GET /respondents/1/edit
  def edit
  end

  # POST /respondents
  # POST /respondents.json
  def create
    @respondent = Respondent.new(respondent_params)
    @respondent.survey = @survey

    respond_to do |format|
      if @respondent.save
        format.html { redirect_to survey_respondent_path(@respondent.survey, @respondent), notice: 'Respondent was successfully created.' }
        format.json { render :show, status: :created, location: @respondent }
      else
        format.html { render :new }
        format.json { render json: @respondent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /respondents/1
  # PATCH/PUT /respondents/1.json
  def update
    respond_to do |format|
      if @respondent.update(respondent_params)
        format.html { redirect_to @respondent, notice: 'Respondent was successfully updated.' }
        format.json { render :show, status: :ok, location: @respondent }
      else
        format.html { render :edit }
        format.json { render json: @respondent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /respondents/1
  # DELETE /respondents/1.json
  def destroy
    @respondent.destroy
    respond_to do |format|
      format.html { redirect_to respondents_url, notice: 'Respondent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_respondent
      @respondent = Respondent.find(params[:id])
    end

    def set_survey
      @survey = Survey.find(params[:survey_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def respondent_params
      params.require(:respondent).permit(:name, :survey_id, answers_attributes: [ :id, :question_id, :respondent_id, answer_options_attributes: [ :id, :answer_id, :question_option_id ] ])
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @questions = @survey.questions.build
    2.times { @question_options = @questions.question_options.build }
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title, questions_attributes: [ :id, :title, question_options_attributes: [ :id, :title ] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/respondents_helper.rb
module RespondentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/respondents/_form.html.erb
<%= form_for( [ @survey, @respondent ] ) do |form| %>
  <% if respondent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(respondent.errors.count, "error") %> prohibited this respondent from being saved:</h2>

      <ul>
      <% respondent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :survey_id %>
    <%= form.text_field :survey_id %>
  </div>

  <div class="field">
    <% @survey.questions.each do |question| %>
      <%= question.title %>
      <%= form.fields_for :answers do |answer| %>
        <%= answer.hidden_field :question_id, value: question.id %>
        <% question.question_options.each do |question_option| %>
          <%= answer.fields_for :answer_options do |answer_option| %>
            <%= answer_option.radio_button :question_option_id, question_option.id %>
            <%= answer_option.label :question_option_id, question_option.title %>          
          <% end %>
        <% end %>  
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/respondents/edit.html.erb
<h1>Editing Respondent</h1>

<%= render 'form', respondent: @respondent %>

<%= link_to 'Show', @respondent %> |
<%= link_to 'Back', respondents_path %>

app/views/respondents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Respondents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Survey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @respondents.each do |respondent| %>
      <tr>
        <td><%= respondent.name %></td>
        <td><%= respondent.survey %></td>
        <td><%= link_to 'Show', @survey.respondent, respondent %></td>
        <td><%= link_to 'Edit', edit_respondent_path(respondent) %></td>
        <td><%= link_to 'Destroy', respondent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Respondent', new_respondent_path %>

app/views/respondents/new.html.erb
<%= render 'form', respondent: @respondent %>

app/views/respondents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @respondent.name %>
</p>

<p>
  <strong>Survey:</strong>
  <%= @respondent.survey.title %>
</p>

<p>
  <% @respondent.answers.each do |answer| %>
    <%= answer.question.title %> <br>
    <% answer.answer_options.each do |answer_option| %>
      <%= answer_option.question_option.title %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_survey_respondent_path(@respondent) %> |

app/views/surveys/_form.html.erb
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :survey_title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.fields_for :questions do |question| %>
      
      <%= question.label :question_title %>
      <%= question.text_field :title %> 
      
      <%= question.fields_for :question_options do |question_option| %>
        <%= question_option.label :question_option_title %>
        <%= question_option.text_field :title %>
      <% end %>

    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.title %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @survey.title %>
</p>

<p>
  <% @survey.questions.each do |question| %>
    <%= question.title %>
    <% question.question_options.each do |question_option| %>
      <%= question_option.title %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>